name: Deploye Lambda

on:
  push:
    branches:
      - dev

jobs:
  deploye_lambda_insert_to_db:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: npm install
        working-directory: ./insert-to-db
        env:
          CI: true
        run: npm ci
      
      - name: compile
        working-directory: ./insert-to-db
        run: npm run-script build
      
      - name: zip
        working-directory: ./insert-to-db
        run:  zip -j  insert-to-db.zip compiled/index.js

      - name: aws cli deployement
        working-directory: ./insert-to-db
        run: aws lambda update-function-code --function-name sohm-insert-to-db --zip-file fileb://insert-to-db.zip

  deploying_puppeteer_function:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: npm install
        working-directory: ./insert-into-sohm
        env:
          CI: true
        run: npm ci
      
      - name: compile
        working-directory: ./insert-into-sohm
        run: npm run-script build
      
      - name: copy elements-mapping.json
        working-directory: ./insert-into-sohm
        run: cp elements-mapping.json compiled/

      - name: zip
        working-directory: ./insert-into-sohm
        run:  zip -j  insert-to-sohm.zip compiled/*
      
      - name: aws cli deployement
        working-directory: ./insert-into-sohm
        run: aws lambda update-function-code --function-name sohm-puppeteer-fill-data --zip-file fileb://insert-to-sohm.zip